- openapi/worldbank/client.bal
* Set request format to json by default and not allow for users to configure the request type
* Handle failures when error payload or empty payload was received
* Return empty array when invalid payload was received
* All the responses from the WorldBank API endpoint will be in json format
> Set request format to json by default and revamp error handling

- openapi/zoom/openapi.yaml
- openapi/zoom/types.bal
$subject
There was an empty record generated without any fields due to an allOf related issue. Generated fields to that record by fixing the definition.
> Add fields to an empty record in Zoom Connector

- openapi/medium/client.bal
- openapi/medium/openapi.yaml
- openapi/medium/types.bal
Fixing the connector return type "PostDetails"  data mapping issue
- Unit tests 
> Done
> Done
> JDK 11, Ballerina Swan Lake Alpha5
> Fix post operation data mapping issue

- openapi/bitbucket/Dependencies.toml
- openapi/medium/Dependencies.toml
Adding dependencies locking for the connectors: bitbucket, medium
- Unit tests 
> Done
> Done
> JDK 11, Ballerina Swan Lake Alpha5
> Add dependency locks for Bitbucket and Medium

- openapi/covid19/client.bal
- openapi/worldbank/client.bal
It is a temporary fix done for the OOM found in the ballerina/http module. The issue has been fixed in the slalpha5.8 patch release.
> Remove cache disable temp fix

- openapi/newsapi/Ballerina.toml
- openapi/newsapi/Dependencies.toml
- openapi/newsapi/Module.md
- openapi/newsapi/Package.md
> Update dependencies to Swan Lake Beta 2 in News API connector Dependencies.toml
>  Update connector documentations
> Update dependencies in News API connector to Swan Lake Beta 2 and update documentations

- openapi/vonage.numberinsight/client.bal
- openapi/vonage.numberinsight/types.bal
> Add missing license headers for vonage.numberinsight connector
> Add missing license headers for vonage.numberinsight connector
> Add missing license headers for vonage.numberinsight connector
> 
JDK 11
SL Beta 2
Ubuntu 20.04
> [SL Beta 2] Add missing license headers for vonage.numberinsight connector

- openapi/vonage.numberinsight/client.bal
- openapi/vonage.numberinsight/types.bal
> Add missing license headers for vonage.numberinsight connector
> Add missing license headers for vonage.numberinsight connector
> Add missing license headers for vonage.numberinsight connector
> 
JDK 11
SL Alpha 5
Ubuntu 20.04
> [SL Alpha 5] Add missing license headers for vonage.numberinsight connector

- openapi/ebay.compliance/.gitignore
- openapi/ebay.compliance/Ballerina.toml
- openapi/ebay.compliance/Dependencies.toml
- openapi/ebay.compliance/Module.md
- openapi/ebay.compliance/Package.md
- openapi/ebay.compliance/client.bal
- openapi/ebay.compliance/openapi.yml
- openapi/ebay.compliance/types.bal
resolves  https://github.com/wso2-enterprise/choreo/issues/7140
adding eBay connector which belongs under the e-commerce category.
https://developer.ebay.com/api-docs/sell/compliance/overview.html
> [SLalpha5] add ebay.compliance connector

- openapi/nytimes.newswire/Dependencies.toml
> Dependencies.toml file was commited with SL Beta 2 dependencies for the `slalpha5 branch`. Update the Dependencies.toml file with SL Alpha 5 dependencies.
> Update the Dependencies.toml file with SL Alpha 5 dependencies.
> Update the Dependencies.toml file with SL Alpha 5 dependencies.
> 
JDK 11
Ballerina Beta 2
Ubuntu 20.04
> [SL Alpha 5] Update the Dependencies.toml file with SL Alpha 5 dependencies for Nytimes newswire connector

- openapi/ebay.compliance/.gitignore
- openapi/ebay.compliance/Ballerina.toml
- openapi/ebay.compliance/Dependencies.toml
- openapi/ebay.compliance/Module.md
- openapi/ebay.compliance/Package.md
- openapi/ebay.compliance/client.bal
- openapi/ebay.compliance/openapi.yml
- openapi/ebay.compliance/types.bal
resolves  https://github.com/wso2-enterprise/choreo/issues/7140
adding eBay connector which belongs under the e-commerce category.
https://developer.ebay.com/api-docs/sell/compliance/overview.html
> [SLbeta2] add ebay.compliance connector

- openapi/googleapis.blogger/client.bal
- openapi/googleapis.blogger/openapi.yml
- openapi/googleapis.tasks/client.bal
- openapi/googleapis.tasks/openapi.yml
> $Subject
> Remove optional auth parameters in operations
> Remove optional auth parameters in from openapi.yml
> 
JDK 11
Ballerina Beta 2
Ubuntu 20.04
> [SL Beta 2] Remove optional auth parameters in operations

- openapi/googleapis.youtube.analytics/client.bal
- openapi/googleapis.youtube.analytics/openapi.yaml
- openapi/googleapis.youtube.analytics/types.bal
- Remove usage of EmptyResponse record from openapi.yaml
- Re-generate connector with the latest openapi tool (Tool version - 13th Aug 2021 )
- Fix https://github.com/wso2-enterprise/choreo/issues/7704
JDK 11
Ballerina SLBeta2
> [SLBeta2] Re-generate youtube analytics connector with latest tool

- openapi/interzoid.globalpageload/.gitignore
- openapi/interzoid.globalpageload/Ballerina.toml
- openapi/interzoid.globalpageload/Dependencies.toml
- openapi/interzoid.globalpageload/Module.md
- openapi/interzoid.globalpageload/Package.md
- openapi/interzoid.globalpageload/client.bal
- openapi/interzoid.globalpageload/openapi.yml
- openapi/interzoid.globalpageload/types.bal
Add interzoid.globalpageload connector
> Add interzoid.globalpageload connector

- openapi/interzoid.currencyrate/.gitignore
- openapi/interzoid.currencyrate/Ballerina.toml
- openapi/interzoid.currencyrate/Dependencies.toml
- openapi/interzoid.currencyrate/Module.md
- openapi/interzoid.currencyrate/Package.md
- openapi/interzoid.currencyrate/client.bal
- openapi/interzoid.currencyrate/openapi.yml
- openapi/interzoid.currencyrate/types.bal
Add interozoid.currencyrate connector
https://interzoid.com/services/getcurrencyrate
> Yes
> Add interozoid.currencyrate connector

- .github/workflows/daily-build.yml
Earlier the name of this repo was `ballerinax-openapi-connectors`
But now we have renamed it as `openapi-connectors`
In this PR, the repo name in build failure notification is updated
> Update new repoName in build failure notification

- openapi/godaddy.certificates/Ballerina.toml
Previously we removed SNAPSHOT from the version of all the connectors.
Only in godaddy.certificates connector, it was missed.
In this PR, upcoming version of godaddy.certificates is corrected as `1.0.2`
> Remove SNAPSHOT from godaddy.certificates version

- openapi/vimeo/client.bal
- openapi/vimeo/openapi.yml
- openapi/vimeo/types.bal
- openapi/vimeo/utils.bal
- When we tried to re-generate this connector with latest tool, got the following error. So, the irrelevant requestBody entries had to be removed from the openapi.yml
```
DELETE operation cannot have a requestBody. Error at operationId: removeChannelModerators
DELETE operation cannot have a requestBody. Error at operationId: removeVideosFromChannel
DELETE operation cannot have a requestBody. Error at operationId: deleteVodRegions
```
- After updating the openapi.yml, connector is re-generated.
> Regenerate Vimeo connector with latest tool

- openapi/stripe/client.bal
- openapi/stripe/types.bal
Query parameters with composed schemas were missing from `queryParamEncoding` map due to the [bug](https://github.com/ballerina-platform/openapi-tools/issues/798) in Ballerina openapi tool. 
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/202
- Bug fix in stripe connector query parameter encoding
Following methods were tested
- listInvoices
- getInvoise
- getCustomer
- listCoupons
* Ballerina Version: SL Beta3 & SL Beta6
* Operating System: Ubuntu 20.04
* Java SDK: JDK 11
> Bug fix in stripe connector query parameter encoding

- openapi/livestorm/Ballerina.toml
- openapi/livestorm/Dependencies.toml
- openapi/livestorm/openapi.yml
- openapi/livestorm/types.bal
Regenerate `Livestorm` connector using Ballerina SL Beta6
Changes were added to OpenAPI specification of the Livestorm connector due to nullable fields in return for response not mapped properly earlier.
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/233
- Regenerate `Livestorm` connector using Ballerina SL Beta6
Not tested
> Regenerate Livestorm connector to handle null

- openapi/livestorm/Dependencies.toml
- openapi/livestorm/openapi.yml
- openapi/livestorm/types.bal
Regenerate `Livestorm` connector using Ballerina SL Beta6
Changes were added to OpenAPI specification of the Livestorm connector due to nullable fields in return for response not mapped properly earlier.
- Regenerate `Livestorm` connector using Ballerina SL Beta6
Not tested
> Add nullable field to avatar_link attribute

- openapi/livestorm/Ballerina.toml
- openapi/livestorm/Dependencies.toml
- openapi/livestorm/openapi.yml
- openapi/livestorm/types.bal
Regenerate `Livestorm` connector using Ballerina SL Beta6
Changes were added to the OpenAPI specification of the Livestorm connector due to a mismatch in the data types returned in the response and the data type mentioned in the official OpenAPI. Although it is an official OpenApi from Livestorm. Data types returned are different in the actual response.
- Regenerate `Livestorm` connector using Ballerina SL Beta6
Not tested
> [Livestorm connector] Fix data type mismatches between response and records

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- Bump `actions/checkout` version to the latest version (`v2`) in the github workflows
> Bump `actions/checkout` version to `v2`

- openapi/hubspot.crm.contact/client.bal
- openapi/hubspot.crm.contact/openapi.yaml
- Remove irrelevant slash in the hubspot service url
- Remove irrelevant slash in the hubspot service url
> Remove irrelevant slash in the service url of hubspot.crm.contact connector

- tool-tests/6-allOf/openapi.yaml
Fix for invalid default value is given for a string field
> Update test workflow sample OpenAPI file for `beezup.merchant` connector  

- openapi/interzoid.weatherzip/Dependencies.toml
- openapi/interzoid.weatherzip/openapi.yml
- openapi/interzoid.weatherzip/types.bal
Update `WeatherData` record in connector `interzoid.weatherzip`
This was missing some optional fields.
> Update `WeatherData` record in connector `interzoid.weatherzip`

- .github/workflows/release.yml
- In the release workflow, the hash update part failing with an error.
- Need to update Github action versions and fix the workflow error
> Update GH action versions and fix workflow error

- openapi/aayu.mftg.as2/Dependencies.toml
- openapi/aayu.mftg.as2/openapi.yaml
- openapi/aayu.mftg.as2/types.bal
Fix record mapping issue.
`SuccessfulMessageSubmitResponse` should have optional fields.
```
public type SuccessfulMessageSubmitResponse record {
string message?;
string as2MessageId?;
};
```
> Fix record mapping issue

- openapi.properties
- openapi/alfresco/Ballerina.toml
- openapi/quickbooks.online/Ballerina.toml
We released 2 connectors in this release https://github.com/ballerina-platform/openapi-connectors/releases/tag/v2.2.8
| Connector Name | Version |
| ---------------- | ------- |
| alfresco |1.0.1|
|quickbooks.online|1.2.2|
This PR is to do the version bump and hash update after the release.
> Update hashes and bump versions after v2.2.8 release

- .github/workflows/daily-build.yml
- Remove central token from daily build workflow
> Remove central token from daily build workflow

- .github/workflows/ci.yml
Earlier we added a temperorary fix to point to dev BCentral in the ci.yaml via https://github.com/ballerina-platform/openapi-connectors/pull/738
https://github.com/ballerina-platform/openapi-connectors/pull/738#issuecomment-1291365462
This PR is to remove that temporary fix and point to the Prod BCentral
> Point to prod central in ci.yaml

- openapi/stripe/Ballerina.toml
- openapi/stripe/Dependencies.toml
- openapi/stripe/Package.md
- openapi/stripe/client.bal
- openapi/stripe/types.bal
Including ability to call
`GET /v1/subscription_items/:id/usage_record_summaries`
Related issue: https://github.com/wso2-enterprise/choreo/issues/18935
- Add remote operation to retrieve usage_record_summaries for stripe connector
N/A
* Ballerina Version: 2201.2.3
> Add remote operation to get usage_record_summaries

- openapi/worldbank/Ballerina.toml
- openapi/worldbank/Package.md
- openapi/worldbank/types.bal
- Update worldbank connector to use HTTP 1.1
Currently the connector uses HTTP 2.0 and gives the below error
```
error: Forbidden {"statusCode":403,"headers":{"Connection":["keep-alive"],"content-length":["179"],"Content-Type":["text/html"],"Date":["Fri, 28 Apr 2023 04:05:49 GMT"],"Server":["Microsoft-Azure-Application-Gateway/v2"]},"body":"<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>
"}
```
But when changing to HTTP 1.1, it works fine
> Update worldbank connector to use http 1.1

- openapi/azure.openai.text/Ballerina.toml
- openapi/azure.openai.text/openapi.yaml
- openapi/azure.openai.text/types.bal
Intermittent Payload binding error occurs when using Azure OpenAI Text connector.
```
PayloadBindingClientError (\"Payload binding failed: \'map<json>\' value cannot be converted to \'azure.openai.text:Inline_response_200\': \n\t\tfield \'choices[0].finish_reason\' in record \'azure.openai.text:Inline_response_200_choices\' should be of type \'string\', found \'()\'\",error(\"{ballerina/lang.value}ConversionError\",message=\"\'map<json>\' value cannot be converted to \'azure.openai.text:Inline_response_200\': \n\t\tfield \'choices[0].finish_reason\' in record \'azure.openai.text:Inline_response_200_choices\' should be of type \'string\', found \'()\'\"))
```
Fixes [# (issue)](https://github.com/wso2-enterprise/choreo/issues/21060)
- Fixes Intermittent Payload …
> Fix Payload binding error in Azure OpenAI Text connector

- openapi/openai.audio/Ballerina.toml
- openapi/openai.chat/Ballerina.toml
- openapi/openai.embeddings/Ballerina.toml
- openapi/openai.finetunes/Ballerina.toml
- openapi/openai.images/Ballerina.toml
- openapi/openai.moderations/Ballerina.toml
- openapi/openai.text/Ballerina.toml
- openapi/shopify.admin/Ballerina.toml
- openapi/shopify.admin/openapi.yml
- openapi/shopify.admin/types.bal
Fix shopify order adjustment data mapping issue
Fixes # https://github.com/wso2-enterprise/internal-support-ballerina/issues/417
- Fix shopify order adjustment data mapping issue
* Ballerina Version: 2201.4.1
* Operating System: Ubuntu 20.04
* Java SDK: 11
> Fix shopify order adjustment data mapping issue

- .github/workflows/ci.yml
- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
$subject to release openai.chat and azure.openai.chat connectors on SL update 8.
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
* Java SDK: 
> Update ballerina version in release workflows

- openapi/googleapis.cloudfilestore/types.bal
$title
fixes: https://github.com/ballerina-platform/ballerina-library/issues/6684
> Update broken link in types.bal 
