ballerina-platform/openapi-connectors

- .github/workflows/ci.yml
$title
Change the CI workflow triggering branch to `main` from `master`.
> Change the CI workflow trigger PR branch to main from master

- openapi/openweathermap/Package.md
- openapi/openweathermap/client.bal
- openapi/openweathermap/openap.yaml
- openapi/openweathermap/types.bal
$title
Resolves https://github.com/wso2-enterprise/choreo/issues/5237
* Add doc comments to the bal files 
* Refactor Package.md
> Update openweathermap connector

- openapi/covid19/client.bal
- openapi/covid19/openapi.yaml
- openapi/covid19/types.bal
$ title
Resolves https://github.com/wso2-enterprise/choreo/issues/5236
Add doc comments for bal files.
> Update Covid-19 connector

- openapi/openweathermap/openap.yaml
- openapi/openweathermap/types.bal
> Update typos in the doc

- openapi/covid19/Ballerina.toml
- openapi/openweathermap/Ballerina.toml
- openapi/worldbank/Ballerina.toml
> Bump connector version in covid19, openweathermap, worldbank

- openapi/covid19/Ballerina.toml
- openapi/covid19/Dependencies.toml
- openapi/openweathermap/Ballerina.toml
- openapi/openweathermap/Dependencies.toml
- openapi/worldbank/Ballerina.toml
- openapi/worldbank/Dependencies.toml
- openapi/worldbank/client.bal
- openapi/worldbank/openapi.yaml
> Lock http client version to 1.1.0-alpha8 and released 0.3.0

- build.gradle
Comment out the code-generation execution during the release process.
> Comment out code-generation during the release

- openapi/worldbank/Ballerina.toml
> Bump worldbank connector version 0.4.0

- build.gradle
- Enable code build during the release process.
> Enable code build in release task

- openapi/covid19/client.bal
- openapi/openweathermap/client.bal
- openapi/worldbank/client.bal
The OpenAPI tool now updated not to generate the code with checkpanic.
> Remove checkpanic in the generated code

- openapi/covid19/Ballerina.toml
- openapi/openweathermap/Ballerina.toml
- openapi/worldbank/Ballerina.toml
> Bump covid19, openweathermap, worldbank connector versions

- openapi/openweathermap/client.bal
- openapi/openweathermap/openap.yaml
* Remove `string[]` from `map<string|string[]> apiKeys`
* Improve the documention
Improve the usability of the connector
> Update ApiKeysConfig record

- openapi/covid19/client.bal
- openapi/covid19/openapi.yaml
> Fix for spelling mistake in Covid19 Connector

- openapi/covid19/Ballerina.toml
- openapi/openweathermap/Ballerina.toml
- openapi/zoom/Ballerina.toml
> Bump version of covid19, openweathermap, zoom connectors

- openapi/bitbucket/Package.md
- openapi/bitbucket/client.bal
- openapi/bitbucket/openapi.yaml
- openapi/bitbucket/types.bal
Adding filtering and sorting facility for the listing operations such as list issues, workspaces, pull requests etc.
Fixes https://github.com/wso2-enterprise/choreo/issues/6161
- Unit tests 
> Done
> Done
> JDK 11, Ballerina Swan Lake Alpha5
> Add filtering and sorting for list operations of Bitbucket connector

- openapi/zoom/Dependencies.toml
- openapi/zoom/Package.md
- openapi/zoom/client.bal
- openapi/zoom/openapi.yaml
- openapi/zoom/types.bal
> Remove all inline records and add separate records
> Add remote functions for all the zoom meeting API endpoints
> Add Dependencies.toml file
Resolves https://github.com/wso2-enterprise/choreo/issues/6177
> Increase usability of the connector
> Java 11
> Build in SL Alpha 5
> Ballerina Open API tool - SL Beta1
> Remove inline records and add new operations to Zoom connector

- openapi/zoom/client.bal
- openapi/zoom/types.bal
Update few optional parameters in response payloads to required
> Update optional parameters in Zoom connector

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/release.yml
- .gitignore
- build.gradle
- openapi.properties
- openapi/covid19/client.bal
- openapi/worldbank/client.bal
- pull_request_template.md
- $title 
- Identify the change whenever a change occurred in any file of the package
- Support for SNAPSHOT versioning
> Add build pipeline improvements

- openapi/zoom/client.bal
- openapi/zoom/types.bal
> Update few optional parameters in response payloads to required 
> Add missing doc comments for records
> Revamp optional parameters in Zoom connector (slalpha5)

- openapi/leanix-integration-api/Ballerina.toml
- openapi/leanix-integration-api/Dependencies.toml
- openapi/leanix-integration-api/Package.md
- openapi/leanix-integration-api/client.bal
- openapi/leanix-integration-api/openapi.yaml
- openapi/leanix-integration-api/types.bal
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
$title
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Add LeanIX integration API connector to main branch

- openapi/zoom/Module.md
- openapi/zoom/Package.md
> Update zoom connector documentation

- openapi/covid19/Module.md
- openapi/covid19/Package.md
> Update covid19 documentation

- openapi/themoviedb/Ballerina.toml
- openapi/themoviedb/Module.md
- openapi/themoviedb/Package.md
- openapi/themoviedb/client.bal
> Update The Movie Database documentation in slalpha5 branch

- openapi/themoviedb/Ballerina.toml
- openapi/themoviedb/Module.md
- openapi/themoviedb/Package.md
- openapi/themoviedb/client.bal
> Update The Movie Database documentation main branch

- openapi/newsapi/Ballerina.toml
- openapi/newsapi/Module.md
> Add repository tag in Ballerina.toml for News API openapi connector slalpha5 branch

- openapi/jira/Ballerina.toml
> Add repository tag in Ballerina.toml for Jira openapi connector for slalpha5 branch

- .github/workflows/ci.yml
- .github/workflows/release.yml
> As there is an issue encountered with the `ballerina:nightly` image, as a temporary workaround SL eta2 will be used.
> $title
> Ubuntu 20.04, OpenJDK 11, Ballerina Swan Lake Beta2
> Update CI and Release Workflows to Use Swan Lake Beta2

- openapi/openweathermap/Module.md
- openapi/openweathermap/Package.md
> update openweathermap connector documentation

- openapi/jira/Ballerina.toml
> Add repository tag in Ballerina.toml for Jira openapi connector for main branch

- openapi/newsapi/Ballerina.toml
- openapi/newsapi/Module.md
> Add repository tag in Ballerina.toml for News API openapi connector main branch

- openapi/spotify/Module.md
- openapi/spotify/Package.md
> Update spotify connector documentation

- openapi/sendgrid/Module.md
- openapi/sendgrid/Package.md
- openapi/sendgrid/client.bal
- openapi/sendgrid/types.bal
> Remove inline records and move them into seperate records
> U[date connector documentation
> Revamp sendgrid connector

- openapi/worldbank/Module.md
- openapi/worldbank/Package.md
> Update worldbank documentation

- openapi/covid19/client.bal
- openapi/covid19/types.bal
> $subject
> JDK 11
> Swan Lake Beta 2
> Remove inline records in covid19 connector

- openapi/soundcloud/Ballerina.toml
- openapi/soundcloud/Dependencies.toml
- openapi/soundcloud/Module.md
- openapi/soundcloud/Package.md
- openapi/soundcloud/client.bal
- openapi/soundcloud/openapi.yml
- openapi/soundcloud/types.bal
> $subject
fixes: https://github.com/wso2-enterprise/choreo/issues/6794
> No
> No
> https://developers.soundcloud.com/docs/api/explorer/open-api
> Add soundcloud connector to main branch

- openapi/soundcloud/Ballerina.toml
- openapi/soundcloud/Dependencies.toml
- openapi/soundcloud/Module.md
- openapi/soundcloud/Package.md
- openapi/soundcloud/client.bal
- openapi/soundcloud/openapi.yml
- openapi/soundcloud/types.bal
> $subject
fixes: https://github.com/wso2-enterprise/choreo/issues/6794
> No
> No
> Ballerina Swan Lake SLAlpha5
> https://developers.soundcloud.com/docs/api/explorer/open-api
> Add soundcloud connector to SLAlpha5 branch

- openapi/gitlab/client.bal
> Fix for the error issue in apiKeys header map

- openapi/gitlab/client.bal
> [SL Alpha5] Fix for the error issue in apiKeys header map

- openapi/ably/Package.md
- openapi/bisstats/Package.md
> Update package.md tables of Bisstats and Ably connectors
> Update package.md tables
> Update package.md tables
> 
JDK11
Ballerina Beta 2
Ubuntu 20.04
> [SL Beta 2] Update package.md tables for Ably and Bisstats connectors

- openapi/ably/Package.md
- openapi/bisstats/Package.md
> Update package.md tables of Bisstats and Ably connectors
> Update package.md tables
> Update package.md tables
> 
JDK11
Ballerina Alpha 5
Ubuntu 20.04
> [SL Alpha 5] Update package.md tables for Ably and Bisstats connectors

- openapi/boxapi/Ballerina.toml
- openapi/boxapi/Module.md
- openapi/boxapi/Package.md
- openapi/isbndb/Module.md
- openapi/isbndb/Package.md
- openapi/jira/Module.md
- openapi/jira/Package.md
- openapi/jira/client.bal
- openapi/livestorm/Module.md
- openapi/livestorm/Package.md
- openapi/newsapi/Ballerina.toml
- openapi/newsapi/Module.md
- openapi/newsapi/Package.md
- openapi/newsapi/client.bal
- openapi/orbitcrm/Module.md
- openapi/themoviedb/Module.md
- openapi/themoviedb/Package.md
- openapi/themoviedb/client.bal
> Update Package.md format to latest format
> Update Package.md format in main branch

- openapi/boxapi/Ballerina.toml
- openapi/boxapi/Module.md
- openapi/boxapi/Package.md
- openapi/isbndb/Module.md
- openapi/isbndb/Package.md
- openapi/jira/Module.md
- openapi/jira/Package.md
- openapi/jira/client.bal
- openapi/livestorm/Module.md
- openapi/livestorm/Package.md
- openapi/newsapi/Module.md
- openapi/newsapi/Package.md
- openapi/newsapi/client.bal
- openapi/orbitcrm/Module.md
- openapi/themoviedb/Module.md
- openapi/themoviedb/Package.md
- openapi/themoviedb/client.bal
> Update Package.md format to latest format
> Update Package.md format in slalpha5 branch

- openapi/bitbucket/Module.md
- openapi/bitbucket/Package.md
- openapi/bulksms/Module.md
- openapi/bulksms/Package.md
- openapi/soundcloud/Module.md
- openapi/soundcloud/Package.md
> $subject
> Code coverage information
> Details about the test cases and coverage
> Documentation updates for Bitbucket, BulkSMS and SoundCloud connectors to main branch

- openapi/leanix.integrationapi/Ballerina.toml
- openapi/leanix.integrationapi/Package.md
- openapi/leanix.integrationapi/client.bal
- openapi/leanix.integrationapi/types.bal
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
Update missing doc comments and modify Package.md table format
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of …
> Update LeanIX connector in alpha5 branch

- openapi/leanix.integrationapi/Ballerina.toml
- openapi/leanix.integrationapi/Package.md
- openapi/leanix.integrationapi/client.bal
- openapi/leanix.integrationapi/types.bal
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
- Update missing doc comments and modify Package.md table format
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes …
> Update LeanIX connector in main branch

- openapi/bitbucket/Module.md
- openapi/bitbucket/Package.md
- openapi/bulksms/Module.md
- openapi/bulksms/Package.md
- openapi/soundcloud/Module.md
- openapi/soundcloud/Package.md
> $subject
> Code coverage information
> Details about the test cases and coverage
> Ballerina Swan Lake Alpha5
> Documentation update for bitbucket, bulkSMS and soundcloud to slalpha5 branch

- openapi/bitbucket/Module.md
- openapi/bulksms/Module.md
- openapi/soundcloud/Module.md
> $subject
> Code coverage information
> Details about the test cases and coverage
> Update documentations - bitbucket, bulksms and soundcloud to main branch

- openapi/pocketsmith/.gitignore
- openapi/pocketsmith/Ballerina.toml
- openapi/pocketsmith/Dependencies.toml
- openapi/pocketsmith/Module.md
- openapi/pocketsmith/Package.md
- openapi/pocketsmith/client.bal
- openapi/pocketsmith/openapi.yaml
- openapi/pocketsmith/types.bal
> $subject.
https://raw.githubusercontent.com/pocketsmith/api/master/openapi.json
> OpenJDK 11, Ballerina Swan Lake Alpha 5, Ubuntu 20.04
> [Alpha 5] Add pocketsmith connector to the alpha5 branch

- openapi/elmah/.gitignore
- openapi/elmah/Ballerina.toml
- openapi/elmah/Dependencies.toml
- openapi/elmah/Module.md
- openapi/elmah/Package.md
- openapi/elmah/client.bal
- openapi/elmah/openapi.yaml
- openapi/elmah/types.bal
> $subject
> OpenJDK 11, Ballerina Swan Lake Alpha 5, Ubuntu 20.04
> [Alpha 5] Add elmah connector to alpha5 branch

- openapi/hubspot.analytics/.gitignore
- openapi/hubspot.analytics/Ballerina.toml
- openapi/hubspot.analytics/Dependencies.toml
- openapi/hubspot.analytics/Module.md
- openapi/hubspot.analytics/Package.md
- openapi/hubspot.analytics/client.bal
- openapi/hubspot.analytics/openapi.yaml
- openapi/hubspot.analytics/types.bal
- openapi/hubspot.events/.gitignore
- openapi/hubspot.events/Ballerina.toml
- openapi/hubspot.events/Dependencies.toml
- openapi/hubspot.events/Module.md
- openapi/hubspot.events/Package.md
- openapi/hubspot.events/client.bal
- openapi/hubspot.events/openapi.yaml
- openapi/hubspot.events/types.bal
> $subject.
Resolves https://github.com/wso2-enterprise/choreo/issues/6800
> Connector generation done using Ballerina OpenAPI tool
> OpenJDK 11, Ballerina Swan Lake Alpha 5, Ubuntu 20.04
> [SLAlpha 5] Add HubSpot analytics and HubSpot events connectors

- openapi/hubspot.files/.gitignore
- openapi/hubspot.files/Ballerina.toml
- openapi/hubspot.files/Dependencies.toml
- openapi/hubspot.files/Module.md
- openapi/hubspot.files/Package.md
- openapi/hubspot.files/client.bal
- openapi/hubspot.files/openapi.yaml
- openapi/hubspot.files/types.bal
- openapi/hubspot.marketing/.gitignore
- openapi/hubspot.marketing/Ballerina.toml
- openapi/hubspot.marketing/Dependencies.toml
- openapi/hubspot.marketing/Module.md
- openapi/hubspot.marketing/Package.md
- openapi/hubspot.marketing/client.bal
- openapi/hubspot.marketing/openapi.yaml
- openapi/hubspot.marketing/types.bal
> $subject.
Resolves https://github.com/wso2-enterprise/choreo/issues/6800
> Connector generation done using Ballerina OpenAPI tool
> OpenJDK 11, Ballerina Swan Lake Alpha 5, Ubuntu 20.04
> [SL Alpha 5] Add HubSpot files and HubSpot Marketing connectors to alpha5 branch

- openapi/ebay.negotiation/Ballerina.toml
- openapi/ebay.negotiation/Dependencies.toml
- openapi/ebay.negotiation/Module.md
- openapi/ebay.negotiation/Package.md
- openapi/ebay.negotiation/client.bal
- openapi/ebay.negotiation/openapi.yml
- openapi/ebay.negotiation/types.bal
> $Subject
> Ballerina Swan Lake SLAlpha5
>https://developer.ebay.com/api-docs/sell/negotiation/overview.html
> [SL Alpha5] Add ebay.negotiation connector

- openapi/ebay.finances/Ballerina.toml
- openapi/ebay.finances/Dependencies.toml
- openapi/ebay.finances/Module.md
- openapi/ebay.finances/Package.md
- openapi/ebay.finances/client.bal
- openapi/ebay.finances/openapi.yml
- openapi/ebay.finances/types.bal
> $subject
Fixes https://github.com/wso2-enterprise/choreo/issues/6994
> Adding e-commerce  connectors
> Ballerina Swan Lake Alpha5
> https://developer.ebay.com/api-docs/sell/static/sell-landing.html
> [SL Alpha5] Add ebay.finances connector

- openapi/openfigi/Ballerina.toml
- openapi/openfigi/Dependencies.toml
- openapi/openfigi/Module.md
- openapi/openfigi/Package.md
- openapi/openfigi/client.bal
- openapi/openfigi/openapi.yml
- openapi/openfigi/types.bal
$subject
> Ballerina Swan Lake Alpha5
> [SLAlpha5] Add openfigi connector

- openapi/ebay.negotiation/Ballerina.toml
- openapi/ebay.negotiation/Dependencies.toml
- openapi/ebay.negotiation/Module.md
- openapi/ebay.negotiation/Package.md
- openapi/ebay.negotiation/client.bal
- openapi/ebay.negotiation/openapi.yml
- openapi/ebay.negotiation/types.bal
> $Subject
>https://developer.ebay.com/api-docs/sell/negotiation/overview.html
> [SL Beta5] Add eBay negotiation connector

- openapi/hubspot.analytics/.gitignore
- openapi/hubspot.analytics/Ballerina.toml
- openapi/hubspot.analytics/Dependencies.toml
- openapi/hubspot.analytics/Module.md
- openapi/hubspot.analytics/Package.md
- openapi/hubspot.analytics/client.bal
- openapi/hubspot.analytics/openapi.yaml
- openapi/hubspot.analytics/types.bal
- openapi/hubspot.events/.gitignore
- openapi/hubspot.events/Ballerina.toml
- openapi/hubspot.events/Dependencies.toml
- openapi/hubspot.events/Module.md
- openapi/hubspot.events/Package.md
- openapi/hubspot.events/client.bal
- openapi/hubspot.events/openapi.yaml
- openapi/hubspot.events/types.bal
> $subject.
> Connector generation done using Ballerina OpenAPI tool
> Describe migration steps and platforms on which migration has been tested
> Add HubSpot analytics and HubSpot events connectors

- openapi/hubspot.files/.gitignore
- openapi/hubspot.files/Ballerina.toml
- openapi/hubspot.files/Dependencies.toml
- openapi/hubspot.files/Module.md
- openapi/hubspot.files/Package.md
- openapi/hubspot.files/client.bal
- openapi/hubspot.files/openapi.yaml
- openapi/hubspot.files/types.bal
- openapi/hubspot.marketing/.gitignore
- openapi/hubspot.marketing/Ballerina.toml
- openapi/hubspot.marketing/Dependencies.toml
- openapi/hubspot.marketing/Module.md
- openapi/hubspot.marketing/Package.md
- openapi/hubspot.marketing/client.bal
- openapi/hubspot.marketing/openapi.yaml
- openapi/hubspot.marketing/types.bal
> $subject.
> Connector generation done using Ballerina OpenAPI tool
> [SL Beta 2] Add HubSpot files and HubSpot Marketing connectors to main branch

- openapi/ebay.finances/Ballerina.toml
- openapi/ebay.finances/Dependencies.toml
- openapi/ebay.finances/Module.md
- openapi/ebay.finances/Package.md
- openapi/ebay.finances/client.bal
- openapi/ebay.finances/openapi.yml
- openapi/ebay.finances/types.bal
> $subject
Fixes https://github.com/wso2-enterprise/choreo/issues/6994
> Adding e-commerce  connectors
> https://developer.ebay.com/api-docs/sell/static/sell-landing.html
> [SL Beta2]Add ebay.finances connector

- openapi/openfigi/client.bal
> Fix OpenFIGI connector build issue

- openapi/elmah/.gitignore
- openapi/elmah/Ballerina.toml
- openapi/elmah/Dependencies.toml
- openapi/elmah/Module.md
- openapi/elmah/Package.md
- openapi/elmah/client.bal
- openapi/elmah/openapi.yaml
- openapi/elmah/types.bal
> [Beta 2] Add elmah connector to main branch

- openapi/covid19/Module.md
- openapi/covid19/Package.md
- openapi/covid19/client.bal
- openapi/covid19/openapi.yaml
- openapi/covid19/types.bal
> $subject
> Update covid19 connector to comply with latest Ballerina Open API tool. 
> [SL Beta 2] Covid19 connector doc comment update and update client class to isolated. 

- openapi/azure.datalake/Ballerina.toml
- openapi/azure.datalake/Module.md
- openapi/azure.datalake/Package.md
- openapi/azure.datalake/client.bal
- openapi/azure.datalake/openapi.yaml
- openapi/azure.datalake/types.bal
> $subject
> Update Module.md and Package.md to the new structure
> [Beta 2] Update documentations and add isolated class fix for Azure Data Lake connector

- openapi/gitlab/Ballerina.toml
- openapi/gitlab/Module.md
- openapi/gitlab/Package.md
- openapi/gitlab/client.bal
- openapi/gitlab/openapi.yaml
- openapi/gitlab/types.bal
> $subject
> Update Module.md and Package.md to the new structure
> [Beta 2] Update documentations and add isolated class fix for GitLab connector

- openapi/themoviedb/Ballerina.toml
- openapi/trello/Module.md
- openapi/trello/Package.md
- openapi/trello/client.bal
- openapi/trello/openapi.yaml
- openapi/trello/types.bal
> $subject
> Update Module.md and Package.md to the new structure
> [Beta 2] Update the documentations and fix for isolated class in Trello connector

- openapi/sendgrid/Module.md
- openapi/sendgrid/Package.md
- openapi/sendgrid/client.bal
- openapi/sendgrid/openapi.yaml
- openapi/sendgrid/types.bal
> $subject
> Update sendgrid connector to comply with latest Ballerina Open API tool. 
> [SL Beta 2] Sendgrid connector doc comment update and client class to isolated update

- openapi/spotify/Module.md
- openapi/spotify/Package.md
- openapi/spotify/client.bal
- openapi/spotify/openapi.yaml
- openapi/spotify/types.bal
> $subject
> Update spotify connector to comply with latest Ballerina Open API tool. 
> [SL Beta 2] Spotify connector documentation update and client class to isolated update

- openapi/vonage.numberinsight/Ballerina.toml
- openapi/vonage.numberinsight/Module.md
- openapi/vonage.numberinsight/Package.md
- openapi/vonage.numberinsight/client.bal
- openapi/vonage.numberinsight/openapi.yml
- openapi/vonage.numberinsight/types.bal
> $subject
Resolves https://github.com/wso2-enterprise/choreo/issues/7225
> 
> [SL Beta 2] Update docs & isolate client class for Vonage NumberInsight connector

- openapi/isbndb/Ballerina.toml
- openapi/isbndb/Dependencies.toml
- openapi/isbndb/Module.md
- openapi/isbndb/Package.md
- openapi/isbndb/client.bal
- openapi/isbndb/openapi.yaml
- openapi/isbndb/types.bal
> $subject
- Unit tests 
> Done
> Done
> [SL Beta 2] Update ISBNdb connector documentation and isolated client class

- openapi/livestorm/Ballerina.toml
- openapi/livestorm/Dependencies.toml
- openapi/livestorm/Module.md
- openapi/livestorm/Package.md
- openapi/livestorm/client.bal
- openapi/livestorm/openapi.yml
- openapi/livestorm/types.bal
> $subject
- Unit tests 
> Done
> Done
> [SL Beta 2] Update LiveStorm connector documentation and isolated client class

- openapi/themoviedb/Ballerina.toml
- openapi/themoviedb/Module.md
- openapi/themoviedb/Package.md
- openapi/themoviedb/client.bal
- openapi/themoviedb/openapi.yml
- openapi/themoviedb/types.bal
> $subject
- Unit tests 
> Done
> Done
> [SL Beta 2] Update TMDB connector documentation and isolated client class

- openapi/newsapi/Ballerina.toml
- openapi/newsapi/Module.md
- openapi/newsapi/Package.md
- openapi/newsapi/client.bal
- openapi/newsapi/openapi.yml
> $subject
- Unit tests 
> Done
> Done
> [SL Beta 2] Update News API connector documentation and isolated client class

- openapi/vonage.verify/Ballerina.toml
- openapi/vonage.verify/Module.md
- openapi/vonage.verify/Package.md
- openapi/vonage.verify/client.bal
- openapi/vonage.verify/openapi.yml
- openapi/vonage.verify/types.bal
> $subject
Resolves https://github.com/wso2-enterprise/choreo/issues/7226
> 
> [SL Beta 2] Update docs & isolate client class for Vonage Verify connector

- openapi/bulksms/Ballerina.toml
- openapi/bulksms/Module.md
- openapi/bulksms/Package.md
- openapi/bulksms/client.bal
- openapi/bulksms/openapi.yml
> $subject
- 
> https://www.bulksms.com/developer/json/v1/#section/Overview
> [SL Beta2]Update BulkMSMS documentation & Add isolated client class

- openapi/vonage.numbers/Ballerina.toml
- openapi/vonage.numbers/Dependencies.toml
- openapi/vonage.numbers/Module.md
- openapi/vonage.numbers/Package.md
- openapi/vonage.numbers/client.bal
- openapi/vonage.numbers/openapi.yml
> $subject
Resolves https://github.com/wso2-enterprise/choreo/issues/7272
> 
> [SL Beta 2] Update docs & isolate client class for Vonage numbers connector

- openapi/ebay.negotiation/Module.md
- openapi/ebay.negotiation/client.bal
- openapi/ebay.negotiation/openapi.yml
> [SL Beta2] Add eBay negotiation connector documentation structure changes

- openapi/vonage.sms/Ballerina.toml
- openapi/vonage.sms/Module.md
- openapi/vonage.sms/Package.md
- openapi/vonage.sms/client.bal
- openapi/vonage.sms/openapi.yml
- openapi/vonage.sms/types.bal
> $subject
Resolves https://github.com/wso2-enterprise/choreo/issues/7276
> 
> [SL Beta 2] Update docs & isolate client class for Vonage sms connector

- openapi/bisstats/Ballerina.toml
- openapi/bisstats/Module.md
- openapi/bisstats/Package.md
- openapi/bisstats/client.bal
- openapi/bisstats/openapi.yaml
> $subject
Resolves https://github.com/wso2-enterprise/choreo/issues/7278
> 
> [SL Beta 2] Update docs & isolate client class for BIS stats connector

- openapi/ably/Ballerina.toml
- openapi/ably/Module.md
- openapi/ably/Package.md
- openapi/ably/client.bal
- openapi/ably/openapi.yaml
- openapi/ably/types.bal
> $subject
Resolves https://github.com/wso2-enterprise/choreo/issues/7282
> 
> [SL Beta 2] Update docs & isolate client class for Ably connector

- openapi/zoom/Module.md
- openapi/zoom/Package.md
- openapi/zoom/client.bal
- openapi/zoom/openapi.yaml
- openapi/zoom/types.bal
> Move inline records to defined schemas
> Update documentation
> Update client class to isolated
> Update zoom connector to comply with latest Ballerina Open API tool. 
> [SL Beta 2] Update zoom connector documentation and inline records. 

- openapi/medium/Module.md
- openapi/medium/Package.md
- openapi/medium/client.bal
- openapi/medium/openapi.yaml
- openapi/medium/types.bal
> $subject
> Ballerina Swan Lake 20
> [SL Beta2] Update Medium connector docs structure & Add isolated client class

- openapi/bitbucket/Module.md
- openapi/bitbucket/Package.md
- openapi/bitbucket/client.bal
- openapi/bitbucket/openapi.yaml
- openapi/bitbucket/types.bal
> [SL Beta2] Update Bit bucket connector documentation structure and Add isolated client class 

- openapi/jira/Ballerina.toml
- openapi/jira/Module.md
- openapi/jira/Package.md
- openapi/jira/client.bal
- openapi/jira/openapi.json
- openapi/jira/types.bal
> $subject
- Unit tests 
> Done
> Done
> [SL Beta 2] Update Jira connector documentation and isolated client class

- openapi/soundcloud/Module.md
- openapi/soundcloud/Package.md
- openapi/soundcloud/client.bal
- openapi/soundcloud/openapi.yml
- openapi/soundcloud/types.bal
> [SL Beta2] Update soundcloud doc structure & Add isolated client class

- openapi/ebay.account/Ballerina.toml
- openapi/ebay.account/Dependencies.toml
- openapi/ebay.account/Module.md
- openapi/ebay.account/Package.md
- openapi/ebay.account/client.bal
- openapi/ebay.account/openapi.yml
- openapi/ebay.account/types.bal
> $subject
> https://developer.ebay.com/api-docs/sell/account/overview.html
> [SL Beta2] Add eBay account connector

- .gitignore
- openapi/leanix.integrationapi/Module.md
- openapi/leanix.integrationapi/Package.md
- openapi/leanix.integrationapi/client.bal
- openapi/leanix.integrationapi/openapi.yaml
- openapi/leanix.integrationapi/types.bal
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
$subject
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …
> Regenerate LeanIX connector with slbeta2 openapi

- openapi/journey/.gitignore
- openapi/journey/Ballerina.toml
- openapi/journey/Dependencies.toml
- openapi/journey/Module.md
- openapi/journey/Package.md
- openapi/journey/client.bal
- openapi/journey/openapi.yaml
- openapi/journey/types.bal
> [Beta 2] Add journey.io connector to the main branch

- openapi/godaddy.certificates/Ballerina.toml
- openapi/godaddy.certificates/Dependencies.toml
- openapi/godaddy.certificates/Module.md
- openapi/godaddy.certificates/Package.md
- openapi/godaddy.certificates/client.bal
- openapi/godaddy.certificates/openapi.yml
- openapi/godaddy.certificates/types.bal
> $subject
> https://developer.godaddy.com/getstarted
> [SL Beta2 ] Add GoDaddy certificates connector

- openapi/googleapis.bigquery/Ballerina.toml
- openapi/googleapis.bigquery/Dependencies.toml
- openapi/googleapis.bigquery/Module.md
- openapi/googleapis.bigquery/Package.md
- openapi/googleapis.bigquery/client.bal
- openapi/googleapis.bigquery/openapi.yml
- openapi/googleapis.bigquery/types.bal
>$subject
> Adding google API connectors
Fixes https://github.com/wso2-enterprise/choreo/issues/7467
> https://cloud.google.com/bigquery/docs/reference/rest
> [SLBeta2] Add Google BigQuery connector

- openapi/godaddy.shoppers/Ballerina.toml
- openapi/godaddy.shoppers/Dependencies.toml
- openapi/godaddy.shoppers/Module.md
- openapi/godaddy.shoppers/Package.md
- openapi/godaddy.shoppers/client.bal
- openapi/godaddy.shoppers/openapi.yml
- openapi/godaddy.shoppers/types.bal
> $subject
> https://developer.godaddy.com/doc/endpoint/shoppers
> [SL Beta2] Add Godaddy shoppers connector

- openapi/azure.keyvault/.gitignore
- openapi/azure.keyvault/Ballerina.toml
- openapi/azure.keyvault/Dependencies.toml
- openapi/azure.keyvault/Module.md
- openapi/azure.keyvault/Package.md
- openapi/azure.keyvault/client.bal
- openapi/azure.keyvault/openapi.yaml
- openapi/azure.keyvault/types.bal
> $subject
- Resolves https://github.com/wso2-enterprise/choreo/issues/7544
> [SL Beta2] Add Azure Key Vault connector to the main branch

- openapi/azure.timeseries/.gitignore
- openapi/azure.timeseries/Ballerina.toml
- openapi/azure.timeseries/Dependencies.toml
- openapi/azure.timeseries/Module.md
- openapi/azure.timeseries/Package.md
- openapi/azure.timeseries/client.bal
- openapi/azure.timeseries/openapi.yaml
- openapi/azure.timeseries/types.bal
> [SL Beta2] Add Azure Timesieries connector to the main branch

- openapi/vimeo/.gitignore
- openapi/vimeo/Ballerina.toml
- openapi/vimeo/Dependencies.toml
- openapi/vimeo/Module.md
- openapi/vimeo/Package.md
- openapi/vimeo/client.bal
- openapi/vimeo/openapi.yml
- openapi/vimeo/types.bal
Add Vimeo connector
resolves https://github.com/wso2-enterprise/choreo/issues/7645
> [SLBeta2] Add Vimeo connector

- openapi/godaddy.agreements/.gitignore
- openapi/godaddy.agreements/Ballerina.toml
- openapi/godaddy.agreements/Dependencies.toml
- openapi/godaddy.agreements/Module.md
- openapi/godaddy.agreements/Package.md
- openapi/godaddy.agreements/client.bal
- openapi/godaddy.agreements/openapi.yml
- openapi/godaddy.agreements/types.bal
> $subject
> https://developer.godaddy.com/doc/endpoint/domains
> [SL Beta2 ] Add Godaddy Agreements connector

- openapi/godaddy.domains/Ballerina.toml
- openapi/godaddy.domains/Dependencies.toml
- openapi/godaddy.domains/Module.md
- openapi/godaddy.domains/Package.md
- openapi/godaddy.domains/client.bal
- openapi/godaddy.domains/openapi.yml
- openapi/godaddy.domains/types.bal
> $subject
> https://developer.godaddy.com/doc/endpoint/domains
> [SL Beta2 ] Add Godaddy Domains connector

- openapi/azure.iotcentral/.gitignore
- openapi/azure.iotcentral/Ballerina.toml
- openapi/azure.iotcentral/Dependencies.toml
- openapi/azure.iotcentral/Module.md
- openapi/azure.iotcentral/Package.md
- openapi/azure.iotcentral/client.bal
- openapi/azure.iotcentral/openapi.yaml
- openapi/azure.iotcentral/types.bal
> [SL Beta2] Add Azure IoT Central connector to main branch

- openapi/owler/.gitignore
- openapi/owler/Ballerina.toml
- openapi/owler/Dependencies.toml
- openapi/owler/Module.md
- openapi/owler/Package.md
- openapi/owler/client.bal
- openapi/owler/openapi.yaml
- openapi/owler/types.bal
> $subject
- Resolves https://github.com/wso2-enterprise/choreo/issues/7649
> [SL Beta2] Add Owler connector to the main branch

- openapi/googleapis.youtube.reporting/client.bal
- Re-generate connector with the latest openapi tool (Tool version - 13th Aug 2021 )
- Fix https://github.com/wso2-enterprise/choreo/issues/7705
JDK 11
Ballerina SLBeta2
> [SLBeta2] Re-generate Youtube reporting connector with latest tool

- openapi/onepassword/.gitignore
- openapi/onepassword/Ballerina.toml
- openapi/onepassword/Dependencies.toml
- openapi/onepassword/Module.md
- openapi/onepassword/Package.md
- openapi/onepassword/client.bal
- openapi/onepassword/openapi.yaml
- openapi/onepassword/types.bal
> [SL Beta2] Add 1Password connector into the main branch

- openapi/azure.iothub/.gitignore
- openapi/azure.iothub/Ballerina.toml
- openapi/azure.iothub/Dependencies.toml
- openapi/azure.iothub/Module.md
- openapi/azure.iothub/Package.md
- openapi/azure.iothub/client.bal
- openapi/azure.iothub/openapi.yml
- openapi/azure.iothub/types.bal
add Azure IoT Hub connector
resolves https://github.com/wso2-enterprise/choreo/issues/7749
> [SLBeta2] Add Azure IoT Hub connector

- openapi/azure.textanalytics/Module.md
Update link in Module.md for token generation
> Update link in Module.md 

- openapi/godaddy.abuse/Module.md
- openapi/godaddy.agreements/Module.md
- openapi/godaddy.certificates/Module.md
- openapi/godaddy.countries/Module.md
- openapi/godaddy.domains/Module.md
- openapi/godaddy.orders/Module.md
- openapi/godaddy.shoppers/Module.md
- openapi/godaddy.subscriptions/Module.md
> Update the module.md to the agreed structure.
> Provides a better user-friendly and common structure for all connectors.
> Remove the conf.toml update part from the obtain tokens section of the prerequisites
> [SLBeta2] Update Module.md - prerequisites sections of the GoDaddy connectors

- openapi/interzoid.globaltime/Ballerina.toml
Update Interzoid Global time connector
> Update Interzoid Globaltime connector

- openapi/bigquery.datatransfer/.gitignore
- openapi/bigquery.datatransfer/Ballerina.toml
- openapi/bigquery.datatransfer/Dependencies.toml
- openapi/bigquery.datatransfer/Module.md
- openapi/bigquery.datatransfer/Package.md
- openapi/bigquery.datatransfer/client.bal
- openapi/bigquery.datatransfer/openapi.yml
- openapi/bigquery.datatransfer/types.bal
Add Bigquery data transfer connector
resolves https://github.com/wso2-enterprise/choreo/issues/7684
> [SLBeta2] Add Bigquery data transfer connector

- openapi/apideck.lead/.gitignore
- openapi/apideck.lead/Ballerina.toml
- openapi/apideck.lead/Dependencies.toml
- openapi/apideck.lead/Module.md
- openapi/apideck.lead/Package.md
- openapi/apideck.lead/client.bal
- openapi/apideck.lead/openapi.yaml
- openapi/apideck.lead/types.bal
- openapi/apideck.proxy/.gitignore
- openapi/apideck.proxy/Ballerina.toml
- openapi/apideck.proxy/Dependencies.toml
- openapi/apideck.proxy/Module.md
- openapi/apideck.proxy/Package.md
- openapi/apideck.proxy/client.bal
- openapi/apideck.proxy/openapi.yaml
- openapi/apideck.proxy/types.bal
> $subject
- Resolves https://github.com/wso2-enterprise/choreo/issues/7806
> [SL Beta 2] Add Apideck lead and proxy connectors to the main branch

- openapi/earthref.fiesta/.gitignore
- openapi/earthref.fiesta/Ballerina.toml
- openapi/earthref.fiesta/Dependencies.toml
- openapi/earthref.fiesta/Module.md
- openapi/earthref.fiesta/Package.md
- openapi/earthref.fiesta/client.bal
- openapi/earthref.fiesta/openapi.yaml
- openapi/earthref.fiesta/types.bal
> $subject
> Add OpenAPI connector for EarthRef.org's FIESTA API.
> JDK 11
Ballerina SL Beta2
Ubuntu 20.04
> [SL Beta2] Add EarthRef.org's FIESTA connector

- openapi/azure.anomalydetector/.gitignore
- openapi/azure.anomalydetector/Ballerina.toml
- openapi/azure.anomalydetector/Dependencies.toml
- openapi/azure.anomalydetector/Module.md
- openapi/azure.anomalydetector/Package.md
- openapi/azure.anomalydetector/client.bal
- openapi/azure.anomalydetector/openapi.yml
- openapi/azure.anomalydetector/types.bal
Add Azure anomaly detector connector
> [SLBeta2] Add Azure anomaly detector connector

- openapi/dynamics365.bussiness_central/.gitignore
- openapi/dynamics365.bussiness_central/Ballerina.toml
- openapi/dynamics365.bussiness_central/Dependencies.toml
- openapi/dynamics365.bussiness_central/Module.md
- openapi/dynamics365.bussiness_central/Package.md
- openapi/dynamics365.bussiness_central/client.bal
- openapi/dynamics365.bussiness_central/openapi.yaml
- openapi/dynamics365.bussiness_central/types.bal
> $subject
- Resolves https://github.com/wso2-enterprise/choreo/issues/7982
> $subject
> $subject
> JDK 11
Ubuntu 20.04
> https://dynamics.microsoft.com/en-us/business-central/overview/
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v1.0/enabling-apis-for-dynamics-nav
>The connector has more than 300 operations
>This openAPI supports the v1.0 of the Dynamics 365 business central API but the latest version available is v2.0
> [SL Beta 3] Add Dynamics 365 Bussiness Central connector to the main branch

- openapi/interzoid.statedata/.gitignore
- openapi/interzoid.statedata/Ballerina.toml
- openapi/interzoid.statedata/Dependencies.toml
- openapi/interzoid.statedata/Module.md
- openapi/interzoid.statedata/Package.md
- openapi/interzoid.statedata/client.bal
- openapi/interzoid.statedata/openapi.yml
- openapi/interzoid.statedata/types.bal
add interzoid.statedata connector
> [SLBeta3] Add interzoid.statedata connector

- openapi/interzoid.weatherzip/.gitignore
- openapi/interzoid.weatherzip/Ballerina.toml
- openapi/interzoid.weatherzip/Dependencies.toml
- openapi/interzoid.weatherzip/Module.md
- openapi/interzoid.weatherzip/Package.md
- openapi/interzoid.weatherzip/client.bal
- openapi/interzoid.weatherzip/openapi.yml
- openapi/interzoid.weatherzip/types.bal
add Interzoid.weatherzip connector
> [SLBeta3] Add Interzoid.weatherzip connector

- openapi/pagerduty/.gitignore
- openapi/pagerduty/Ballerina.toml
- openapi/pagerduty/Dependecies.toml
- openapi/pagerduty/Module.md
- openapi/pagerduty/Package.md
- openapi/pagerduty/client.bal
- openapi/pagerduty/openapi.yml
- openapi/pagerduty/types.bal
> Add Pagerduty connector

- openapi/interzoid.mailinfo/.gitignore
- openapi/interzoid.mailinfo/Ballerina.toml
- openapi/interzoid.mailinfo/Dependencies.toml
- openapi/interzoid.mailinfo/Module.md
- openapi/interzoid.mailinfo/Package.md
- openapi/interzoid.mailinfo/client.bal
- openapi/interzoid.mailinfo/openapi.yml
- openapi/interzoid.mailinfo/types.bal
Add interzoid.emailinfo connector
> [SLBeta3] Add interzoid.emailinfo connector

- openapi/brex.onboarding/.gitignore
- openapi/brex.onboarding/Ballerina.toml
- openapi/brex.onboarding/Dependencies.toml
- openapi/brex.onboarding/Module.md
- openapi/brex.onboarding/Package.md
- openapi/brex.onboarding/client.bal
- openapi/brex.onboarding/openapi.yaml
- openapi/brex.onboarding/types.bal
> $subject 
- Related to https://github.com/wso2-enterprise/choreo/issues/8073
> $subject
> $subject
> JDK 11
Ubuntu 20.04
> https://developer.brex.com/
> Add brex onboarding connector to main branch

- openapi/files.com/Dependencies.toml
- openapi/files.com/client.bal
- openapi/files.com/openapi.yaml
- openapi/files.com/types.bal
> Fix the problem in path query parameter in files.com connector

- openapi/opendesign/.gitignore
- openapi/opendesign/Ballerina.toml
- openapi/opendesign/Dependencies.toml
- openapi/opendesign/Module.md
- openapi/opendesign/Package.md
- openapi/opendesign/client.bal
- openapi/opendesign/openapi.yaml
- openapi/opendesign/types.bal
> $subject 
- Resolves https://github.com/wso2-enterprise/choreo/issues/8126
> $subject
> $subject
> JDK 11
Ubuntu 20.04
> https://opendesign.dev/docs/api-reference/introduction
> Add opendesign connector to main branch

- openapi/interzoid.globalnumberinfo/.gitignore
- openapi/interzoid.globalnumberinfo/Ballerina.toml
- openapi/interzoid.globalnumberinfo/Dependencies.toml
- openapi/interzoid.globalnumberinfo/Module.md
- openapi/interzoid.globalnumberinfo/Package.md
- openapi/interzoid.globalnumberinfo/client.bal
- openapi/interzoid.globalnumberinfo/openapi.yml
- openapi/interzoid.globalnumberinfo/types.bal
Add interzoid.globalnumber connector
> yee
> Add interzoid.globalnumber connector

- openapi/brex.team/.gitignore
- openapi/brex.team/Ballerina.toml
- openapi/brex.team/Dependencies.toml
- openapi/brex.team/Module.md
- openapi/brex.team/Package.md
- openapi/brex.team/client.bal
- openapi/brex.team/openapi.yaml
- openapi/brex.team/types.bal
> $subject 
- Resolves https://github.com/wso2-enterprise/choreo/issues/8073
> $subject
> $subject
> JDK 11
Ubuntu 20.04
> https://developer.brex.com/
> Add brex team connector to the main branch

- openapi/vimeo/Package.md
- openapi/vimeo/client.bal
- openapi/vimeo/openapi.yml
- openapi/vimeo/types.bal
Update Vimeo connector with beta3 functionalities to generate larger clients
> Update Vimeo connector

- openapi/devto/.gitignore
- openapi/devto/Ballerina.toml
- openapi/devto/Dependencies.toml
- openapi/devto/Module.md
- openapi/devto/Package.md
- openapi/devto/client.bal
- openapi/devto/openapi.yml
- openapi/devto/types.bal
add DEV.to connector
https://developers.forem.com/
> Add DEV.to connector

- openapi/plaid/.gitignore
- openapi/plaid/Ballerina.toml
- openapi/plaid/Dependencies.toml
- openapi/plaid/Module.md
- openapi/plaid/Package.md
- openapi/plaid/client.bal
- openapi/plaid/openapi.yaml
- openapi/plaid/types.bal
> $subject 
- Resolves https://github.com/wso2-enterprise/choreo/issues/8049
> $subject
> $subject
> JDK 11
Ubuntu 20.04
> https://plaid.com/docs/api/
> Add plaid connector to the main branch

- openapi/sinch.conversation/.gitignore
- openapi/sinch.conversation/Ballerina.toml
- openapi/sinch.conversation/Dependencies.toml
- openapi/sinch.conversation/Module.md
- openapi/sinch.conversation/Package.md
- openapi/sinch.conversation/client.bal
- openapi/sinch.conversation/openapi.yaml
- openapi/sinch.conversation/types.bal
> $subject 
> $subject
> $subject
> JDK 11
Ubuntu 20.04
> https://developers.sinch.com/
> Add sinch Conversation connector to main branch

- openapi/azure.anomalydetector/client.bal
- openapi/azure.anomalydetector/openapi.yml
- openapi/openweathermap/client.bal
- openapi/openweathermap/openapi.yaml
> $subject
> https://github.com/ballerina-platform/ballerinax-openapi-connectors/pull/452
> Add API Key doc comments

- openapi/saps4hana.itcm.uom/Ballerina.toml
- openapi/saps4hana.itcm.uom/client.bal
- openapi/saps4hana.itcm.uom/openapi.yaml
> Change existing lengthy display name into short meaningful name
> Display label name change for saps4hana unit of measure connector

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
> Trigger PR build on PR sent and push
> Sent notification at daily build failure
> Update github workflows

- openapi/ebay.analytics/Module.md
- openapi/ebay.browse/Module.md
> [slbeta3-batch-1]Add missing Module.md files

- openapi/azure.sqldb/Ballerina.toml
- openapi/azure.sqldb/Dependencies.toml
- openapi/dropbox/Ballerina.toml
- openapi/dropbox/Dependencies.toml
- openapi/karbon/Ballerina.toml
- openapi/karbon/Dependencies.toml
- openapi/launchdarkly/Ballerina.toml
- openapi/launchdarkly/Dependencies.toml
- openapi/listen.notes/Ballerina.toml
- openapi/listen.notes/Dependencies.toml
- openapi/optimizely/Ballerina.toml
- openapi/optimizely/Dependencies.toml
- openapi/power.bi/Ballerina.toml
- openapi/power.bi/Dependencies.toml
- openapi/shopify.admin/Ballerina.toml
- openapi/shopify.admin/Dependencies.toml
- openapi/shortcut/Ballerina.toml
- openapi/shortcut/Dependencies.toml
- openapi/siemens.analytics.anomalydetection/Ballerina.toml
- openapi/siemens.analytics.anomalydetection/Dependencies.toml
- openapi/siemens.iotandstorage.iotfileservice/Ballerina.toml
- openapi/siemens.iotandstorage.iotfileservice/Dependencies.toml
- openapi/text2data/Ballerina.toml
- openapi/text2data/Dependencies.toml
- openapi/whohoststhis/Ballerina.toml
- openapi/whohoststhis/Dependencies.toml
- openapi/zendesk.voice/Ballerina.toml
- openapi/zendesk.voice/Dependencies.toml
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/134
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/128
Related  https://github.com/ballerina-platform/ballerinax-openapi-connectors/pull/546
* Ballerina Version: Ballerina Swan Lake Beta 4
* Java SDK: Java 11
> Remove snapshots of merged connectors

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/release.yml
- build.gradle
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/142
* Ballerina Version: Ballerina swan lake beta 4
* Java SDK: Java 11
> Fix daily build issue

- openapi/stripe/Ballerina.toml
$subject
Related to issue https://github.com/ballerina-platform/ballerina-extended-library/issues/174
> Bump version of stripe connector after release of 1.0.1

- openapi/edocs/client.bal
- openapi/edocs/types.bal
- openapi/edocs/utils.bal
update eDocs connector
Fixes https://github.com/ballerina-platform/openapi-connectors/pull/534
- update eDocs connector
* Ballerina Version: Ballerina Swan Lake Beta 3
* Java SDK: Java 11
> update eDocs connector

- .github/workflows/release.yml
- Change ballerina version to `swan-lake-beta6` in the release.yml
> Update bal version in release.yml

- openapi/openweathermap/Module.md
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/260
- Fix bugs in the Openweathermap connector documentation 
> OpenWeatherMap connector doc update

- openapi/saps4hana.pp.idm/Package.md
Changing the connector name in Package.md
> [Sap s/4hana-PP-IDM connector]Update Package.md for fixing the connector name

- .github/workflows/dev-stg-release.yml
- Add workflow for dev and staging release
- Fix https://github.com/ballerina-platform/ballerina-extended-library/issues/297
> Add workflow for dev and staging release

- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
- Update ballerina docker image version to 2201.0.1 in the release workflows.
> Update ballerina docker image version to 2201.0.1

- openapi/eventbrite/Ballerina.toml
- openapi/eventbrite/Dependencies.toml
- openapi/eventbrite/client.bal
- openapi/eventbrite/openapi.yml
- openapi/eventbrite/types.bal
Unable to call API endpoint due to missing trailing slashes in resource path of Eventbrite connector. This PR fixes this issue.
Add new remote operations to obtain organization ID of Eventbrite connector. This PR adds these new operations.
Resolves https://github.com/ballerina-platform/ballerina-extended-library/issues/338
Resolves https://github.com/ballerina-platform/ballerina-extended-library/issues/337
- Add missing trailing slashes in resource paths of remote operations
- Add new remote operations to obtain organization ID of Eventbrite
**Test …
> [Eventbrite] Add new operations & add missing trailing slashes in resource paths of existing remote operations

- openapi/asana/Ballerina.toml
- openapi/asana/Dependencies.toml
- openapi/asana/openapi.yaml
- openapi/asana/types.bal
Regenerate connector to fix nullable record in Asana
* Ballerina Version: 2201.0.1
* Java SDK: 11
> Regenerate connector to fix nullable record in Asana

- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
- Bump ballerina version to 2201.0.2
> Bump ballerina version to 2201.0.2

- openapi/gotomeeting/Ballerina.toml
- openapi/gototraining/Ballerina.toml
- openapi/gotowebinar/Ballerina.toml
- openapi/livestorm/Ballerina.toml
- openapi/logoraisr/Ballerina.toml
- openapi/workday.absencemanagement/Ballerina.toml
- openapi/workday.accountspayable/Ballerina.toml
- openapi/workday.businessprocess/Ballerina.toml
- openapi/workday.common/Ballerina.toml
- openapi/workday.compensation/Ballerina.toml
- openapi/workday.connect/Ballerina.toml
fixes https://github.com/wso2-enterprise/choreo/issues/12741
- Update keywords to fix typo issues
* Ballerina Version: Ballerina 2201.0.2
* Java SDK: Java 11
> Update keywords to fix typo issues

- openapi/aayu.mftg.as2/Ballerina.toml
Revert `aayu.mftg.as2:1.0.0` release
> Revert `aayu.mftg.as2:1.0.0` release

- openapi/aayu.mftg.as2/Dependencies.toml
- openapi/aayu.mftg.as2/client.bal
- Change connector initialization to use username & password
(earlier it was API token)
- Function to obtain a valid token each time when an operation is called.
* Ballerina Version: 2201.0.2
* Java SDK: Java11
> Revamp `aayu.mftg.as2` connector 

- openapi/aayu.mftg.as2/client.bal
- openapi/aayu.mftg.as2/utils.bal
Add review changes for `aayu.mft.as2` connector 
issue https://github.com/ballerina-platform/ballerina-extended-library/issues/279
> Add review changes for `aayu.mftg.as2` connector

- openapi/zoom/Ballerina.toml
- openapi/zoom/Dependencies.toml
- openapi/zoom/Module.md
- openapi/zoom/client.bal
- openapi/zoom/openapi.yaml
Add JWT auth support for the `zoom` connector
This is a feature improvement on the Zoom connector.
Email subject: "Requesting Zoom connector improvement to support JWT Authentication"
Related https://github.com/wso2-enterprise/choreo/issues/13042
> Add JWT auth support for `zoom` connector

- openapi/zoom/Ballerina.toml
- openapi/zoom/Dependencies.toml
- openapi/zoom/Module.md
- openapi/zoom/Package.md
- openapi/zoom/client.bal
- openapi/zoom/openapi.yaml
- openapi/zoom/types.bal
Add following new operations to Zoom connector
- List Meetings [1] - listDashboardMeetings()
- List Meeting Participants [2] - listDashboardMeetingParticipants()
- List Users [3] - listUsers()
[1] https://marketplace.zoom.us/docs/api-reference/zoom-api/methods/#operation/dashboardMeetings
[2] https://marketplace.zoom.us/docs/api-reference/zoom-api/methods/#operation/dashboardMeetingParticipants
[3] https://marketplace.zoom.us/docs/api-reference/zoom-api/methods/#operation/users
Fixes https://github.com/wso2-enterprise/choreo/issues/13329
- Add new operations to list meetings, list meeting participants, list users
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …
> Add new operations to Zoom connector

- openapi/shopify.admin/openapi.yml
- openapi/shopify.admin/types.bal
Update shopify.admin `DiscountApplication` array
Fixes # (issue)
Fixes https://github.com/wso2-enterprise/choreo/issues/13482
> Update shopify.admin `DiscountApplication` array

- openapi/shopify.admin/Ballerina.toml
- openapi/shopify.admin/Dependencies.toml
> Update shopify.admin version

- openapi/shopify.admin/Ballerina.toml
- openapi/shopify.admin/Dependencies.toml
- openapi/shopify.admin/Module.md
- openapi/shopify.admin/client.bal
- openapi/shopify.admin/openapi.yml
- openapi/shopify.admin/types.bal
Improve the Shopify connector addressing concerns in following [thread](https://groups.google.com/g/ballerina-dev/c/IDk20J4bPA0).
- Fix issues in the Module.md
- Add order risks related operations
- Add webhook related operations
Fixes https://github.com/wso2-enterprise/choreo/issues/13582
- Add order risk, webhook related operations and fix issues in the Module.md. 
* Ballerina Version: 2201.0.4
* Operating System: 20.04
* Java SDK: 11
- `x-ballerina-init-description` OpenAPI …
> Improve Shopify connector

- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
> Update workflow files to release in 2201.1.1

- openapi/alfresco/Dependencies.toml
- Update Dependencies.toml for `alfresco` connector
> Update dependencies.toml for `alfresco` connector

- .github/workflows/ci.yml
> Use 2201.1.1 in ci.yaml

- openapi/worldbank/client.bal
- openapi/worldbank/types.bal
- openapi/worldbank/utils.bal
Worldbank had some issues after regeneration. Since reverting the change
> Update worldbank conenctor

- .github/workflows/ci.yml
- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
- Update workflows with 2201.3.1
> Update workflows with 2201.3.1

- openapi.properties
- Update hash after release v2.3.1
> Update hash after release v2.3.1

- openapi/stripe/openapi.yaml
$Subject, with a new operation. 
Regeneration not needed as latest release includes the changes. Open API change was missing.
> Modify Open API of Stripe connector

- .github/workflows/ci.yml
- .github/workflows/dev-stg-release.yml
- .github/workflows/release.yml
- Update workflows to use Ballerina 2201.4.1
> Update workflows to use 2201.4.1

- openapi/azure.openai.chat/Package.md
- openapi/azure.openai.embeddings/Package.md
- openapi/azure.openai.text/Package.md
Removed the ballerina version for several azure connectors
Fixes https://github.com/wso2-enterprise/choreo/issues/19293
> Remove the ballerina version for azure connectors

- openapi/quickbooks.online/Ballerina.toml
- openapi/quickbooks.online/Package.md
- openapi/quickbooks.online/client.bal
- openapi/quickbooks.online/types.bal
- openapi/quickbooks.online/utils.bal
- Regenerate quickbooks online connector with latest tool
> Regenerate quickbooks online connector with latest tools

- openapi/openai.audio/original-openapi.yaml
- openapi/openai.chat/original-openapi.yaml
- openapi/openai.embeddings/original-openapi.yaml
- openapi/openai.finetunes/original-openapi.yaml
- openapi/openai.images/original-openapi.yaml
- openapi/openai.moderations/original-openapi.yaml
- openapi/openai.text/original-openapi.yaml
Update original openapi specification yaml files in openai connectors.
> Update original openapi specs in openai connectors

- openapi/openai.audio/README.md
- openapi/openai.chat/README.md
- openapi/openai.embeddings/README.md
- openapi/openai.finetunes/README.md
- openapi/openai.images/README.md
- openapi/openai.moderations/README.md
- openapi/openai.text/README.md
This PR includes README.md files for all OpenAI-related connectors. The format I used is a bit different from the current `Package.md` files.
> Add `README.md` files to all `openai.*` connectors 

- openapi/azure.keyvault/Ballerina.toml
- Update azure.keyvault version to 1.6.0
> Update azure.keyvault version to 1.6.0

- openapi/zendesk.support/Ballerina.toml
- openapi/zendesk.support/Module.md
- openapi/zendesk.support/client.bal
- openapi/zendesk.support/openapi.yaml
- openapi/zendesk.support/types.bal
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes https://github.com/wso2-enterprise/internal-support-ballerina/issues/419
- Update response types of zendesk support connector
NOT TESTED
* Java SDK: 
- `x-ballerina-display` …
> Update types of zendesk support connector

- openapi/beezup.merchant/openapi.yml
- openapi/beezup.merchant/types.bal
- openapi/box/openapi.yaml
- openapi/graphhopper.directions/openapi.yml
- openapi/impala/openapi.yaml
- openapi/livestorm/openapi.yml
- openapi/livestorm/types.bal
- openapi/pagerduty/openapi.yml
$subject
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/560
Fixed connectors : 
- box
- impala
- graphhopper.directions
- pagerduty
- beezup.merchant
- livestorm
- Fix OpenAPI files with spec issues
> Fix OpenAPI files with spec issues

- openapi/beezup.merchant/Ballerina.toml
- openapi/livestorm/Ballerina.toml
- openapi/shopify.admin/Ballerina.toml
- openapi/shopify.admin/openapi.yml
- openapi/shopify.admin/types.bal
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
https://github.com/wso2-enterprise/choreo/issues/23384
fix issue for 
```
Failed to get order details : error PayloadBindingClientError ("Payload binding failed: 'map<json>' value cannot be converted to 'shopify.admin:OrderObject': { { field 'order.shipping_address.latitude' in record 'shopify.admin:CustomerAddress' should be of type 'string?', found '45.4191176' field 'order.shipping_address.longitude' in record 'shopify.admin:CustomerAddress' should be of type 'string?', found '-75.6966166' } }",error("{ballerina/lang.value}ConversionError",message="'map<json>' value cannot be converted to …
```
> Fix data mapping issue for longitude and latitude

- openapi/stripe/client.bal
- openapi/stripe/openapi.yaml
- openapi/stripe/types.bal
- openapi/stripe/utils.bal
> $subject
Fixes: [#5792](https://github.com/ballerina-platform/ballerina-library/issues/5792)
> [2201.0.x] Update stripe-connector to support list-customer functionality

- openapi/ronin/Ballerina.toml
- openapi/ronin/openapi.yml
- openapi/ronin/types.bal
Fixes https://github.com/ballerina-platform/ballerina-library/issues/5787
* Java SDK: 
> Fix invoices and client API issues in ronin connector

- .github/workflows/dev-stg-release.yaml
- Add dev-stg-release.yaml to 2201.0.0
> [2201.0.0] Add dev-stg-release.yaml

- openapi/stripe/Ballerina.toml
- openapi/stripe/client.bal
- openapi/stripe/openapi.yaml
- openapi/stripe/types.bal
$title. This changes are not generated, these are targeted changes copied from the MR #822, This is done this way as generating the client produces enormous amount of diff which eventually breaks the code. And we could not find out the OpenAPI tool version used to generate the client in the base branch. We actually tried with all possible version < 2201.4.1, and for none we could produce the generated code with the contract. (very odd behavior though).
Fixes # (issue)
Related Pull Requests (remove if not relevant)
- #822
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
> [2201.4.1] Update stripe-connector to support list-customer functionality

- openapi/googleapis.cloudfilestore/types.bal
> Update broken link in types.bal

- openapi/elasticsearch/openapi.yaml
- openapi/facebook.ads/openapi.yaml
- openapi/giphy/openapi.yml
- openapi/gitlab/openapi.yaml
- openapi/godaddy.domains/openapi.yml
- openapi/instagram/openapi.yaml
- openapi/openweathermap/openapi.yaml
- openapi/shopify.admin/openapi.yml
This PR adds featured tags for some popular APIs that we want to display as featured in the Godzilla Marketplace.
Related to https://github.com/wso2-enterprise/choreo/issues/33526
> Add featured tags for featured APIs

- openapi/azure.openai.chat/openapi.yaml
- openapi/azure.openai.chat/types.bal
Added a new option `\"required\"` to the `ChatCompletionToolChoiceOption` type in the `types.bal` file. This change enhances the flexibility of tool choice options.
Fixes # https://github.com/ballerina-platform/ballerina-library/issues/7909
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
* Java SDK: 
- `x-ballerina-init-description` OpenAPI …
> Add 'required' option to ChatCompletionToolChoiceOption type

- openapi/azure.openai.chat/openapi.yaml
- openapi/azure.openai.chat/types.bal
Added a new option `\"required\"` to the `ChatCompletionToolChoiceOption` type in the `types.bal` file. This change enhances the flexibility of tool choice options.
Fixes # https://github.com/ballerina-platform/ballerina-library/issues/7909
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
* Java SDK: 
- `x-ballerina-init-description` OpenAPI …
> [2201.8.x] Add 'required' option to ChatCompletionToolChoiceOption type
